// Generated by cli/make_scans.py - do not edit.
// What the vision model read from the scanned attachments, and which values
// this corpus has never seen. Shown to a reviewer; never used to decide a defect.
window.SCANS = {
 "email_512": {
  "BL": {
   "fields": {
    "shipper": {
     "present": true,
     "label_seen": "Shipper",
     "raw": "APRIL FAR EAST (M) SDN BHD"
    },
    "consignee": {
     "present": true,
     "label_seen": "Consignee",
     "raw": "AL GURG STATIONERY LLC"
    },
    "notify_party": {
     "present": true,
     "label_seen": "Notify",
     "raw": "AL GURG STATIONERYLLC"
    },
    "port_of_loading": {
     "present": true,
     "label_seen": "Port of Loading",
     "raw": "NHAVA SHEVA INDIA"
    },
    "port_of_discharge": {
     "present": true,
     "label_seen": "Port of Discharge",
     "raw": "TUTICORIN, INDIA"
    },
    "container_count": {
     "present": true,
     "label_seen": "Containers",
     "raw": "6 x 40'HC"
    },
    "gross_weight_kg": {
     "present": true,
     "label_seen": "Gross Weight",
     "raw": "128,544 KG"
    }
   },
   "untrusted": [
    "notify_party",
    "port_of_loading"
   ]
  },
  "SI": {
   "fields": {
    "shipper": {
     "present": true,
     "label_seen": "Shipper",
     "raw": "APRIL FAR EAST (M) SDN BHD"
    },
    "consignee": {
     "present": true,
     "label_seen": "Consignee",
     "raw": "AL GURG STATIONERY LLC"
    },
    "notify_party": {
     "present": true,
     "label_seen": "Notify",
     "raw": "AL GURG STATIONERY LLC"
    },
    "port_of_loading": {
     "present": true,
     "label_seen": "Port of Loading",
     "raw": "NHAVA SHEVA INDIA"
    },
    "port_of_discharge": {
     "present": true,
     "label_seen": "Port of Discharge",
     "raw": "TUTICORIN, INDIA"
    },
    "container_count": {
     "present": true,
     "label_seen": "Containers",
     "raw": "6 x 40'HC"
    },
    "gross_weight_kg": {
     "present": true,
     "label_seen": "Gross Weight",
     "raw": "128,544 KG"
    }
   },
   "untrusted": [
    "port_of_loading"
   ]
  }
 },
 "email_513": {
  "BL": {
   "fields": {
    "shipper": {
     "present": true,
     "label_seen": "Shipper",
     "raw": "APRIL FINE PAPER TRADING"
    },
    "consignee": {
     "present": true,
     "label_seen": "Consignee",
     "raw": "KPP-ANTALIS (SINGAPORE) PTE LTD."
    },
    "notify_party": {
     "present": true,
     "label_seen": "Notify",
     "raw": "EAST BRIGHT FZ-LLC"
    },
    "port_of_loading": {
     "present": true,
     "label_seen": "Port of Loading",
     "raw": "NHAVA SHEVA INDIA"
    },
    "port_of_discharge": {
     "present": true,
     "label_seen": "Port of Discharge",
     "raw": "VALPARAISO, CHILE"
    },
    "container_count": {
     "present": true,
     "label_seen": "Containers",
     "raw": "10 x 40'HC"
    },
    "gross_weight_kg": {
     "present": true,
     "label_seen": "Gross Weight",
     "raw": "237,750 KG"
    }
   },
   "untrusted": [
    "consignee",
    "port_of_loading"
   ]
  },
  "SI": {
   "fields": {
    "shipper": {
     "present": true,
     "label_seen": "Shipper",
     "raw": "APRIL, FINE PAPER TRADING"
    },
    "consignee": {
     "present": true,
     "label_seen": "Consignee",
     "raw": "KPP-ANTALIS (SINGAPORE) PTE LTD."
    },
    "notify_party": {
     "present": true,
     "label_seen": "Notify",
     "raw": "EAST BRIGHT FZ-LLC"
    },
    "port_of_loading": {
     "present": true,
     "label_seen": "Port of Loading",
     "raw": "NHAVA SHEVA"
    },
    "port_of_discharge": {
     "present": true,
     "label_seen": "Port of Discharge",
     "raw": "VALPARAISO"
    },
    "container_count": {
     "present": true,
     "label_seen": "Containers",
     "raw": "10 x 40'HC"
    },
    "gross_weight_kg": {
     "present": true,
     "label_seen": "Gross Weight",
     "raw": "237,750 KG"
    }
   },
   "untrusted": [
    "shipper",
    "consignee",
    "port_of_loading",
    "port_of_discharge"
   ]
  }
 },
 "email_514": {
  "BL": {
   "fields": {
    "shipper": {
     "present": true,
     "label_seen": "Shipper",
     "raw": "ASIA PACIFIC PAPERBOARD TRADING PTE LTD"
    },
    "consignee": {
     "present": true,
     "label_seen": "Consignee",
     "raw": "EAST BRIGHT FZ-LLC"
    },
    "notify_party": {
     "present": true,
     "label_seen": "Notify",
     "raw": "EAST BRIGHT FZ-LLC"
    },
    "port_of_loading": {
     "present": true,
     "label_seen": "Port of Loading",
     "raw": "NANTONG, CHINA"
    },
    "port_of_discharge": {
     "present": true,
     "label_seen": "Port of Discharge",
     "raw": "GDANSK, POLAND"
    },
    "container_count": {
     "present": true,
     "label_seen": "Containers",
     "raw": "1 x 20'FCL"
    },
    "gross_weight_kg": {
     "present": true,
     "label_seen": "Gross Weight",
     "raw": "22,825 KG"
    }
   },
   "untrusted": []
  },
  "SI": {
   "fields": {
    "shipper": {
     "present": true,
     "label_seen": "Shipper",
     "raw": "ASIA PACIFIC PAPERBOARD TRADING PTE LTD"
    },
    "consignee": {
     "present": true,
     "label_seen": "Consignee",
     "raw": "EAST BRIGHT FZ-LLC"
    },
    "notify_party": {
     "present": true,
     "label_seen": "Notify",
     "raw": "EAST BRIGHT FZ-LLC"
    },
    "port_of_loading": {
     "present": true,
     "label_seen": "Port of Loading",
     "raw": "NANTONG"
    },
    "port_of_discharge": {
     "present": true,
     "label_seen": "Port of Discharge",
     "raw": "GDANSK"
    },
    "container_count": {
     "present": true,
     "label_seen": "Containers",
     "raw": "1 x 20'FCL"
    },
    "gross_weight_kg": {
     "present": true,
     "label_seen": "Gross Weight",
     "raw": "22,825 KG"
    }
   },
   "untrusted": [
    "port_of_loading",
    "port_of_discharge"
   ]
  }
 }
};
