#!/usr/bin/env python3
"""Put the scanned readings where a reviewer can see them.

These five emails escalate as `unreadable`, and they still will: a value read
from an image is not trusted to decide a defect. But "we could not open this"
and "here is what the page says, and these two values we do not trust" are very
different things to hand a person, and only one of them saves them opening the
file themselves.

Written as a small script beside results.js so the page keeps working with no
backend, no key and no network.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / "results" / "vision"
OUT = ROOT / "frontend" / "scans.js"
NAME = re.compile(r"^(email_\d+)_(SI|BL)$")
HEADER = ("// Generated by cli/make_scans.py - do not edit.\n"
          "// What the vision model read from the scanned attachments, and which values\n"
          "// this corpus has never seen. Shown to a reviewer; never used to decide a defect.\n")


def by_email(cache: Path) -> dict[str, dict[str, dict]]:
    found: dict[str, dict[str, dict]] = {}
    for path in sorted(cache.glob("*.json")):
        match = NAME.match(path.stem)
        if not match:
            continue
        email, role = match.group(1), match.group(2)
        found.setdefault(email, {})[role] = json.loads(path.read_text(encoding="utf-8"))

    return found


def main() -> int:
    if not CACHE.is_dir():
        print(f"no readings at {CACHE}; run the vision pass first", file=sys.stderr)
        return 1

    scans = by_email(CACHE)
    OUT.write_text(HEADER + "window.SCANS = " + json.dumps(scans, indent=1, ensure_ascii=False) + ";\n",
                   encoding="utf-8", newline="\n")
    for email, roles in scans.items():
        flagged = sum(len(r["untrusted"]) for r in roles.values())
        print(f"  {email}  {'+'.join(sorted(roles))}  {flagged} value(s) not in the corpus")
    print(f"\n  written to {OUT.relative_to(ROOT)}  ({OUT.stat().st_size} bytes)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
